"""add staff auth fields

Revision ID: 118f4fed3cc1
Revises: b50f31df938d
Create Date: 2026-06-26 20:29:50.642812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118f4fed3cc1'
down_revision: Union[str, Sequence[str], None] = 'b50f31df938d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('staff', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('staff', sa.Column('pin_hash', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'staff', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'pin_hash')
    op.drop_column('staff', 'password_hash')
    op.drop_column('staff', 'email')
    # ### end Alembic commands ###
